name: "🐛 Rapport de bug"
description: Créer une nouvelle issue pour un bug rencontré
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Saisir une description concise du souci rencontré
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Étapes de reproduction"
      description: Saisir les étapes permettant de reproduire le souci
      placeholder: |
        1. Se rendre sur "...."
        2. Cliquer sur "...."
        ....
        x. Obtention de l'erreur
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Captures d'écran"
      description: Si possible, ajouter des captures d''écran qui montrent votre problème
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Ajouter si possible des logs d''exécution (inutile de mettre des backticks, le formattage sera déjà fait)
      render: bash
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: "Navigateurs"
      description: Sur quel navigateur rencontrez-vous le problème ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "Environnement"
      description: Sur quel environnement rencontrez-vous le problème ?
      options:
        - Local
        - Pré-production
        - production
    validations:
      required: true
